#!/bin/bash

usage() {
cat << EOF
usage: $0 options

I created this script because Debian broke my gnome's background settings.

OPTIONS:
   -h      Show this message
   -v      The version of this program
   -b      Your background full name. Eg: mycutepony.jpg
   -o      Background option.

USAGE:
   $ ezy -b mycutepony.jpg -o centered
                           ^ current options: centered, zoom, stretched, scaled, spanned 
EOF
}

while getopts vhb:o: option 
do
    case "${option}" in
	h)
	    usage
	    exit 1
	    ;;
	v)
	    echo 'Ezy version 0.1a'
	    exit 1
	    ;;
	b) 
	    if [ -f $image ]; then
		gsettings set org.gnome.desktop.background picture-uri file:////home/$USER/Immagini/${OPTARG}
		echo 'background changed'
	    else
		echo 'file does not exist'
	    fi
	    ;;
	o)
	    gsettings set org.gnome.desktop.background picture-options ${OPTARG}
	    ;;
	esac
done
